model-name: case-study
technology-instances:
  kubernetes:
    sock-shop:
      kube-config-path: \path\to\.kube\config
      target-namespace: sock-shop
      ignored-container-names:
        - "queue-master"
        - "rabbitmq"
        - "rabbitmq-exporter"
        - "session-db"
#        - "carts"
        - "payment"
        - "shipping"
        - "user"
        - "user-db"
#        - "front-end"
#        - "orders"
#        - "orders-db"
  puppet:
    catalogue:
      user: ubuntu
      ip: 173.212.243.69
      private-key-path: \path\to\.ssh\puppet-master
      environment: production
#  terraform:
#    desktop-local:
#      state-file: \path\to\terraform.tfstate
  cloud-formation:
    catalogue:
      region: eu-central-1
      stack-name: puppet-agent-06
      profile-name: TOSCin

