#cloud-config
puppet:
  install: false
  conf_file: "/etc/puppetlabs/puppet/puppet.conf"
  exec: true
  conf:
    agent:
      server: "puppet-master.fouskas.de"
      certname: "puppet-aws-agent.fouskas.de"
      environment: "alexma"
      runinterval: "1y"

users:
  - default
  - name: catalogue-user



